drops:
mysql:
  user: 'root'
  password: 'asdfasdf'
  host: localhost
  database: ancillarydeterioration
  port: 3306
  poolsize: 10
  connectionTimeout: 10000
  idleTimout: 600000
  maxLifetime: 7200000
